Hello Microverse Project - Pull Request
skabeo/Hello-Microverse pull request #1
Opened 2023-02-14 21:06 UTC by skabeo

2023-02-14 21:13 UTC, skabeo commented
A request to add a html file with a header text and a simple css file styling the header

2023-02-15 09:29 UTC, Shedrack-Sunday requested changes
Hi @skabeo     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 
  
Required Changes ♻️

- [x] Please consider naming your branches with descriptive names as regards your project. the `web-design-branch` you used does not ideally show what the changes you made did. in case of next time, please consider this 👍 

- [ ] Your pull request was not used properly and was not descriptive enough. as seen in the snapshot below, it always uses the first field, and makes it as detailed as possible to explain all changes you made to the project. kindly effect this 👍 

## view:
![image](https://user-images.githubusercontent.com/50990925/218988640-c2aa75df-32dd-4efa-a8d4-8571783c6fef.png)



- [ ] Your README seems not to have been updated with the README template given. Please use this [Link](https://github.com/microverseinc/readme-template) to use the right one with all sections customized to your project 👍 

- [ ] Somehow the changes you made to add all your linters are not showing in the files change, and that's why am reviewing everything here. please d so properly next time 👍 

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-16 15:00 UTC, aamirkhan2478 requested changes
Hi @skabeo , 

![](https://media4.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ All linters are checked
✔️ Descriptive commit messages

 ## Required Changes ♻️
![Screenshot from 2023-02-16 19-27-45](https://user-images.githubusercontent.com/45226848/219394038-7e35c926-df27-417b-bd26-4b743f74b1f0.png)

- [ ] Please add the `build with` section to the README file. and remove the server and database and add HTML and CSS in side the client section.

![Screenshot from 2023-02-16 19-27-58](https://user-images.githubusercontent.com/45226848/219396998-ecfcbb40-3603-4fef-a685-462c0e8644e8.png)

- [ ] Please add the `Key Feature` section also and add your key feature here.

![Screenshot from 2023-02-16 19-28-07](https://user-images.githubusercontent.com/45226848/219397239-e7170017-ddd6-45df-8d4d-d7ce4b8cc7d5.png)

- [ ] Please add a `Live Demo` section and leave it as it is for this project but in future, you can use this link when you will live your website.

![Screenshot from 2023-02-16 19-28-55](https://user-images.githubusercontent.com/45226848/219397830-e6ef1f79-9bd9-4a65-8377-9ba1467cf0ce.png)

- [ ] Please add your social media handles then if someone clicks on your social media handle link it redirects to the specific social media website.

![Screenshot from 2023-02-16 19-29-08](https://user-images.githubusercontent.com/45226848/219398409-0f1e02d1-1bb0-4f81-b1c0-5eedaf862ec4.png)

- [ ] Please add your `Future Feature` section also and add some future features which are you implemented in future.

![Screenshot from 2023-02-16 19-29-18](https://user-images.githubusercontent.com/45226848/219399408-6edc3dc0-f037-4b41-a00a-e9dc1273543b.png)

- [ ] Please add `Contributing`, `Show your support` and  `Acknowledgment` sections.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 15:00 UTC, aamirkhan2478 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Your MIT link is not working kindly fix this link.

2023-02-16 15:00 UTC, aamirkhan2478 commented on README.md
> +
- [ ] Kindly remove this markdown code we don't need this.

2023-02-16 18:48 UTC, Shisui6 approved these changes
Hi @skabeo , 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 10:05 UTC, merged